[package]
name                   = "fsql"
version                = "0.1.0"
edition.workspace      = true
rust-version.workspace = true
description            = "SQL query and mutation engine over the filesystem"
repository.workspace   = true
license.workspace      = true

[dependencies]
sqlparser.workspace   = true
tree-fucker.workspace = true

globset.workspace    = true
regex.workspace      = true
rustix.workspace     = true
serde.workspace      = true
serde_json.workspace = true
uzers.workspace      = true

[lints]
workspace = true
