[package]
name                   = "fsql-cli"
version                = "0.1.0"
edition.workspace      = true
rust-version.workspace = true
description            = "Command line interface for fsql"
repository.workspace   = true
license.workspace      = true

[[bin]]
doc  = false
name = "fsql"
path = "src/main.rs"

[dependencies]
fsql.workspace = true

clap.workspace = true

[lints]
workspace = true
